name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag -l 'v*' | sort -V | tail -n1)
          if [ -z "$latest_tag" ]; then
            echo "version=v1.0.0" >> $GITHUB_OUTPUT
          else
            current_version=$(echo $latest_tag | sed 's/v//')
            major=$(echo $current_version | cut -d. -f1)
            minor=$(echo $current_version | cut -d. -f2)
            
            if [[ $current_version == *"."*"."* ]]; then
              patch=$(echo $current_version | cut -d. -f3)
              new_patch=$((patch + 1))
              echo "version=v$major.$minor.$new_patch" >> $GITHUB_OUTPUT
            else
              echo "version=v$major.$minor.0" >> $GITHUB_OUTPUT
            fi
          fi
          echo "New version will be: ${{ steps.get_latest_tag.outputs.version }}"

      - name: Update version in code
        run: |
          version_without_v=$(echo "${{ steps.get_latest_tag.outputs.version }}" | sed 's/v//')
          sed -i 's/appVersion        = ".*"/appVersion        = "'$version_without_v'"/g' cmd/thighpads/main.go

      - name: Build binaries for multiple platforms
        run: |
          # Windows
          GOOS=windows GOARCH=amd64 go build -v -o thighpads_windows_amd64.exe ./cmd/thighpads
          
          # macOS
          GOOS=darwin GOARCH=amd64 go build -v -o thighpads_darwin_amd64 ./cmd/thighpads
          GOOS=darwin GOARCH=arm64 go build -v -o thighpads_darwin_arm64 ./cmd/thighpads
          
          # Linux
          GOOS=linux GOARCH=amd64 go build -v -o thighpads_linux_amd64 ./cmd/thighpads
          GOOS=linux GOARCH=arm64 go build -v -o thighpads_linux_arm64 ./cmd/thighpads
          
          # Create versioned copies
          cp thighpads_windows_amd64.exe "thighpads_${{ steps.get_latest_tag.outputs.version }}_windows_amd64.exe"
          cp thighpads_darwin_amd64 "thighpads_${{ steps.get_latest_tag.outputs.version }}_darwin_amd64"
          cp thighpads_darwin_arm64 "thighpads_${{ steps.get_latest_tag.outputs.version }}_darwin_arm64"
          cp thighpads_linux_amd64 "thighpads_${{ steps.get_latest_tag.outputs.version }}_linux_amd64"
          cp thighpads_linux_arm64 "thighpads_${{ steps.get_latest_tag.outputs.version }}_linux_arm64"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.version }}
          name: Release ${{ steps.get_latest_tag.outputs.version }}
          draft: true
          generate_release_notes: true
          body: |
            # ThighPads ${{ steps.get_latest_tag.outputs.version }}
                        
            ## Download the appropriate binary for your platform:
            
            - Windows: thighpads_windows_amd64.exe
            - macOS (Intel): thighpads_darwin_amd64
            - macOS (Apple Silicon): thighpads_darwin_arm64
            - Linux (x86_64): thighpads_linux_amd64
            - Linux (ARM64): thighpads_linux_arm64
            
            ## BUGS FIXED:
            -
            -
            
            ## NEW FEATURES:
            -
            -
            
            ## CONTRIBUTORS:
            -
          files: |
            thighpads_windows_amd64.exe
            thighpads_darwin_amd64
            thighpads_darwin_arm64
            thighpads_linux_amd64
            thighpads_linux_arm64
            thighpads_${{ steps.get_latest_tag.outputs.version }}_windows_amd64.exe
            thighpads_${{ steps.get_latest_tag.outputs.version }}_darwin_amd64
            thighpads_${{ steps.get_latest_tag.outputs.version }}_darwin_arm64
            thighpads_${{ steps.get_latest_tag.outputs.version }}_linux_amd64
            thighpads_${{ steps.get_latest_tag.outputs.version }}_linux_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}